name: Run Prettier on Push

on: push

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{html,css,js}
          commit_message: "Run formatter"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
